cat > config/ultimate_hybrid_strategy_config.yml << 'CONFIG_EOF'
# Ultimate Hybrid Trading Strategy Configuration
# GitHub Repository Version 2.0
# https://github.com/your-username/hummingbot-ultimate-hybrid

template_version: 30
strategy: ultimate_hybrid_strategy

# ======================== BASIC CONFIGURATION ========================

# Exchange and Trading Pair
exchange: kucoin
trading_pairs: 
  - WLD-USDT

# Strategy Version Control
version: "2.0"
github_repo: "hummingbot-ultimate-hybrid"

# ======================== GRID TRADING CONFIGURATION ========================

# Grid Strategy Settings
enable_grid: true
grid_mode: "ATR Based"               # Options: "Fixed", "ATR Based", "Percentage"
base_grid_count: 8                   # Number of levels each side (8 buy + 8 sell)
base_spacing_pct: 1.2               # Base spacing percentage
atr_period: 14                       # ATR calculation period
atr_multiplier: 1.5                 # ATR multiplier for dynamic spacing
grid_rebalance_threshold: 0.05      # Rebalance when price moves >5%

# Grid Advanced Settings
grid_order_amount: 0.1              # Order amount per grid level
grid_max_spread: 0.15               # Maximum spread from base price (15%)
grid_min_spread: 0.005              # Minimum spread from base price (0.5%)

# ======================== LAUNCH STRATEGY CONFIGURATION ========================

# Launch Strategy (Kaanermi Method)
enable_launch_strategy: true
launch_time_start: "01:00"          # NY session start (24h format)
launch_time_end: "08:00"            # NY session end (24h format)
needle_body_ratio: 2.0              # Minimum wick/body ratio for needle detection
launch_cooldown_minutes: 30         # Cooldown between launch trades
enable_bias_filter: true            # Use trend bias for launch direction

# Launch Advanced Settings
launch_min_range_pct: 0.005         # Minimum launch range (0.5%)
launch_max_range_pct: 0.050         # Maximum launch range (5.0%)
launch_volume_threshold: 1.2        # Volume multiplier threshold
launch_confirmation_candles: 2      # Candles for confirmation

# ======================== MARKET PROFILE CONFIGURATION ========================

# Market Profile Settings
enable_market_profile: true
mp_session_length: 24               # Hours for market profile calculation
mp_tpo_percent: 70.0               # Value area percentage
mp_price_levels: 20                # Number of price levels for TPO
mp_update_frequency: 30            # Update frequency in minutes

# Market Profile Advanced
mp_poc_weight: 0.4                 # POC influence on grid base price
mp_value_area_filter: true         # Filter trades outside value area
mp_volume_threshold: 1000          # Minimum volume for valid TPO

# ======================== RISK MANAGEMENT CONFIGURATION ========================

# Portfolio Risk Settings
enable_advanced_risk: true
max_portfolio_risk: 12.0           # Maximum portfolio exposure (12%)
max_single_position: 4.0           # Maximum single position size (4%)
max_concurrent_trades: 10          # Maximum number of concurrent trades
min_balance_threshold: 50          # Minimum account balance to trade

# Position Risk Settings
stop_loss_atr: 2.0                 # Stop loss distance in ATR multiples
take_profit_atr: 3.5               # Take profit distance in ATR multiples
risk_reward_ratio: 1.75            # Minimum risk/reward ratio
trailing_stop_enabled: false      # Enable trailing stops
trailing_stop_atr: 1.0             # Trailing stop distance

# Emergency Settings
emergency_stop_drawdown: 20.0      # Emergency stop at 20% drawdown
daily_loss_limit: 5.0              # Daily loss limit (5% of balance)
max_consecutive_losses: 5          # Max consecutive losing trades

# ======================== ADVANCED FILTERS CONFIGURATION ========================

# Volatility Filter
enable_volatility_filter: true
volatility_threshold: 1.5          # Minimum volatility ratio (ATR/Price * 1000)
volatility_period: 20              # Volatility calculation period
high_volatility_threshold: 5.0     # High volatility threshold

# Trend Filter
enable_trend_filter: true
trend_period: 50                   # Trend calculation period
trend_strength_threshold: 0.015    # Minimum trend strength (1.5%)
trend_confirmation_period: 3       # Trend confirmation candles

# Time Filter
enable_time_filter: true
avoid_low_liquidity_hours: true    # Avoid trading during low liquidity
weekend_trading: false             # Disable weekend trading
holiday_filter: true               # Filter major holidays

# Volume Filter
enable_volume_filter: true
min_volume_ratio: 0.5             # Minimum volume vs average
volume_spike_threshold: 3.0        # Volume spike detection
volume_period: 20                  # Volume average period

# ======================== PERFORMANCE OPTIMIZATION ========================

# Execution Settings
order_refresh_time: 30             # Order refresh interval (seconds)
price_update_interval: 5           # Price update interval (seconds)
status_update_interval: 60         # Status display update (seconds)

# Data Management
max_price_history: 500             # Maximum price history records
max_trade_history: 1000            # Maximum trade history records
performance_log_interval: 600      # Performance logging interval (seconds)

# Memory Management
cleanup_interval: 3600             # Memory cleanup interval (seconds)
max_log_size_mb: 100              # Maximum log file size (MB)
log_rotation_days: 7               # Log rotation period (days)

# ======================== GITHUB INTEGRATION ========================

# Repository Settings
auto_update_check: false           # Automatically check for updates
update_check_interval: 86400      # Update check interval (24 hours)
telemetry_enabled: false          # Send anonymous usage data

# Performance Logging
github_performance_log: true       # Log performance for GitHub analytics
export_trade_data: true           # Export trade data for analysis
backup_config: true               # Backup configuration changes

# Development Settings
debug_mode: false                  # Enable debug logging
test_mode: false                   # Enable test mode (paper trading)
simulation_mode: false            # Use simulated market data

# ======================== NOTIFICATION SETTINGS ========================

# Alert Thresholds
profit_alert_threshold: 100       # Profit alert threshold ($)
loss_alert_threshold: -50         # Loss alert threshold ($)
risk_alert_threshold: 10.0        # Risk level alert (10%)

# Status Reporting
hourly_status_report: true         # Send hourly status reports
daily_summary_report: true         # Send daily summary reports
trade_execution_alerts: true      # Alert on trade executions

# ======================== EXCHANGE SPECIFIC SETTINGS ========================

# KuCoin Specific
kucoin_sandbox: false             # Use KuCoin sandbox
kucoin_api_tier: "basic"          # API tier (basic/pro)
kucoin_rate_limit: 10             # API calls per second

# Order Management
order_type_preference: "limit"     # Preferred order type
max_order_age: 3600               # Maximum order age (seconds)
order_size_precision: 4           # Order size decimal precision
price_precision: 4                # Price decimal precision
CONFIG_EOF
